version: '3'

services:

  portainer:
    image: portainer/portainer
    command: -H "tcp://tasks.portainer-agent:9001" --tlsskipverify --no-auth
    ports:
      - "9000:9000"
    networks:
      - portainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  portainer-net:
