{
 "title": "Docker Metricbeat",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Python Rabbit Client Request Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response_time_ms",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Python Client Request Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "container_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "response_time_ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host Normalised Total CPU %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Host Memory Actual Used %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Container CPU %",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "docker.container.labels.com_docker_swarm_task_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "docker.cpu.total.pct",
       "id": "1",
       "meta": {},
       "settings": { "percents": [ "95" ] },
       "type": "percentiles"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}