# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mattjtodd/docker-bionic64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  (1..2).each do |nodeNumber|
    config.vm.define "node-#{nodeNumber}" do |node|
      node.vm.hostname = "node-#{nodeNumber}"
      node.vm.network "private_network", ip: "192.168.50.#{149+nodeNumber}"
    end
  end

end
